#!/bin/bash

##
## ONLY RUN INSIDE A DOCKERIZED TRIPAL DEVTOOLS ENVIRONMENT!
##
## Simple script which calls drush generators from this module
## to create/update the DevTest fields in this module.
##
## The DevTest fields in this module are used to test that the generators
## create working fields. They also provide working examples to developers.
##
## This script should be run whenever updates are made to any of the
## field generators in this module.
##

drush generate tripal:field --yes \
  --answer="tripal_devtools" \
  --answer="devtest_tripal_field" \
  --answer="DevTest Tripal Field" \
  --answer="AUTO GENERATED by Tripal DevTools for Testing." \
  --answer="rdfs:type" \
  --answer="DevtestTripalFieldTypeItem" \
  --answer="devtest_tripal_field_widget" \
  --answer="DevTest Tripal Field Widget" \
  --answer="AUTO GENERATED by Tripal DevTools for Testing." \
  --answer="DevtestTripalFieldWidget" \
  --answer="devtest_tripal_field_formatter" \
  --answer="DevTest Tripal Field Formatter" \
  --answer="AUTO GENERATED by Tripal DevTools for Testing." \
  --answer="DevtestTripalFieldFormatter"
