<?php declare(strict_types = 1);

namespace Drupal\tripal_devtools\Plugin\Field\FieldFormatter;

use Drupal\tripal\TripalField\TripalFormatterBase;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Plugin implementation of the 'devtest_tripal_field_formatter' field formatter for 'devtest_tripal_field'.
 *
 * @FieldFormatter(
 *   id = "devtest_tripal_field_formatter",
 *   label = @Translation("DevTest Tripal Field Formatter"),
 *   description = @Translation("AUTO GENERATED by Tripal DevTools for Testing."),
 *   field_types = {
 *     "devtest_tripal_field"
 *   }
 * )
 */
class DevtestTripalFieldFormatter extends TripalFormatterBase {

  /**
   * {@inheritdoc}
   */
  public function viewElements(FieldItemListInterface $items, $langcode) {
    $elements = [];

    foreach($items as $delta => $item) {
      $elements[$delta] = [
        "#markup" => $item->get("value")->getString(),
      ];
    }

    return $elements;
  }

}

