name: Build and Publish Docker image
on:
  push:
    branches:
      - 4.x

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
        pgsql-version:
          - "13"
        drupal-version:
          - "10.0.x-dev"
          - "10.1.x-dev"
    name: Docker Build (drupal${{ matrix.drupal-version }})
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image.
        with:
          image: tripalproject/tripaldocker-devtools
          tags: drupal${{ matrix.drupal-version }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: "drupalversion=${{ matrix.drupal-version }},phpversion=${{ matrix.php-version}}"
          labels: 'tripal.branch=4.x,drupal.version.label="${{ matrix.label }}",php.version.label="${{ matrix.php-version }}", postgresql.version.label="${{ matrix.pgsql-version }}"'
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build latest using 10.1.x-dev, PHP 8.2, PgSQL 13
        if: ${{ matrix.drupal-version == '10.1.x-dev' && matrix.php-version == '8.2' && matrix.pgsql-version == '13' }}
        with:
          image: tripalproject/tripaldocker-devtools
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: "drupalversion=${{ matrix.drupal-version }},phpversion=${{ matrix.php-version}}"
          labels: 'tripal.branch=4.x,drupal.version.label="${{ matrix.drupal-version }}",php.version.label="${{ matrix.php-version }}", postgresql.version.label="${{ matrix.pgsql-version }}"'
